# Generated by Django 4.2.1 on 2023-05-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uczelnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rodzaj', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=200)),
                ('data_zalozenia', models.DateField()),
                ('numer_uczelni_nadany_przez_ministra', models.IntegerField(unique=True)),
                ('numer_wpisu_do_ewidencji_uczelni_niepublicznych', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KierunekStudiow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('rok_akademicki', models.CharField(max_length=9)),
                ('uczelnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekrutacja.uczelnia')),
            ],
        ),
    ]
