# Generated by Django 4.2.1 on 2023-05-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kierunekstudiow',
            options={'verbose_name': 'Kierunek Studiów', 'verbose_name_plural': 'Kierunki Studiów'},
        ),
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'verbose_name': 'Uczelnia', 'verbose_name_plural': 'Uczelnie'},
        ),
        migrations.RemoveField(
            model_name='uczelnia',
            name='numer_wpisu_do_ewidencji_uczelni_niepublicznych',
        ),
    ]
