# Generated by Django 4.2.1 on 2023-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rekrutacja", "0002_application_ranking"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "program")},
        ),
    ]
