# Generated by Django 4.2.1 on 2023-05-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0002_alter_kierunekstudiow_options_alter_uczelnia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kierunekstudiow',
            name='stopien',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('jednolite', 'Jednolite')], default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kierunekstudiow',
            name='tryb',
            field=models.CharField(choices=[('stacjonarne', 'stacjonarne'), ('niestacjonarne', 'niestacjonarne'), ('online', 'online'), ('hybrydowe', 'hybrydowe')], default='0', max_length=20),
            preserve_default=False,
        ),
    ]
