# Generated by Django 4.2.1 on 2023-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0003_kierunekstudiow_stopien_kierunekstudiow_tryb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='stopien',
            field=models.CharField(choices=[('I stopień', 'I stopień'), ('II stopień', 'II stopień'), ('jednolite', 'jednolite')], max_length=20),
        ),
    ]
