# Generated by Django 4.2.1 on 2023-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekrutacja", "0003_alter_application_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("nieopłacony", "nieopłacony"),
                    ("opłacony", "opłacony"),
                    ("przyjęty", "przyjęty"),
                    ("odrzucony", "odrzucony"),
                    ("na liście rezerwowej", "Na liście rezerwowej"),
                ],
                max_length=50,
            ),
        ),
    ]
