# Generated by Django 4.2.1 on 2023-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0004_alter_kierunekstudiow_stopien'),
    ]

    operations = [
        migrations.AddField(
            model_name='kierunekstudiow',
            name='opis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kierunekstudiow',
            name='typ',
            field=models.CharField(blank=True, choices=[('licencjackie', 'licencjackie'), ('inżynierskie', 'inżynierskie')], max_length=20, null=True),
        ),
    ]
