# Generated by Django 4.2.1 on 2023-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutacja', '0005_kierunekstudiow_opis_kierunekstudiow_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kierunekstudiow',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
